defaults: &defaults
  docker:
    - image: opuscapita/minsk-core-ci:grails-2.4.4-jdk-8u131-nodejs-8.9.4-maven-3.3.9
  working_directory: ~/build

version: 2
jobs:
  build:
    <<: *defaults
    steps:
      - run:
          name: Environment inject.
          command: env_inject.sh

      - checkout

      - restore_cache:
          keys:
            - loaders-{{ .Branch }}-{{ checksum "package.json" }}
            - loaders-{{ .Branch }}
            - loaders

      - run:
          name: "Installing dependencies."
          command: yarn install

      - save_cache:
          key: loaders-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
              - ./node_modules
              - ./yarn.lock

      - run:
          name: "Running lint."
          command: npm run lint

#      - run:
#          name: test
#          command: npm test
#
#      - run:
#          name: upload-coverage
#          command: npm run upload-coverage
#
#      - store_artifacts:
#          path: test-results.xml
#          prefix: tests
#
#      - store_test_results:
#          path: test-results.xml

  build_release::
    <<: *defaults
    steps:
      - run:
          name: Environment inject.
          command: env_inject.sh

      - checkout

      - restore_cache:
          keys:
            - loaders-{{ .Branch }}-{{ checksum "package.json" }}
            - loaders-{{ .Branch }}
            - loaders

      - run:
          name: "Installing dependencies."
          command: yarn install

      - save_cache:
          key: loaders-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
              - ./node_modules
              - ./yarn.lock

      - run:
          name: "Running lint."
          command: npm run lint

      - run:
          name: "Deploy."
          command: npm run publish-release

  release:
    <<: *defaults
    steps:

      - run:
          name: Environment inject
          command: env_inject.sh

      - checkout

      - run:
          name: Executing release scrtipt.
          command: .circleci/release.sh
workflows:
  version: 2
  release-and-build:
    jobs:
      - release:
          filters:
            branches:
              only: release
      - build:
          filters:
            branches:
              ignore:
                - gh-pages
                - release
      - build_release:
          filters:
            tags:
              only: /.*/
            branches:
              ignore: /.*/
